[package]
name = "driver-sqlite"
version = "0.1.0"
description = "SQLite database driver (via sqlx with bundled libsqlite3)"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
async-trait = "0.1.89"
database.workspace = true
libsqlite3-sys.workspace = true
models.workspace = true
sqlx = { workspace = true, features = ["sqlite"] }

[dev-dependencies]
tokio.workspace = true
