[package]
name = "database"
version = "0.1.0"
description = "Common database driver traits and error types"
edition = "2024"
license = "MIT"
publish = false

[features]
default = []
fake = []

[dependencies]
tokio.workspace = true
models.workspace = true
sqlx = { workspace = true, features = ["sqlite", "postgres", "mysql"] }
async-trait = "0.1.89"
