[package]
name = "driver-clickhouse"
version = "0.1.0"
description = "ClickHouse database driver (HTTP-based)"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
async-trait = "0.1.89"
database.workspace = true
models.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
